import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from './components/layout/Sidebar'
import FollowBar from "./components/layout/FollowBar";
import LoginModal from "./components/modals/LoginModal";
import RegisterModal from "./components/modals/RegisterModal";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Stonk Demo",
  description: "Generated by Nunzio.A.Sisto@gmail.com",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    
    <html lang="en">
      <body className={inter.className}>
        {children} 
      </body>
    </html>
    
  );
}
